name: Firmware dumper

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Direct Firmware Link'
        required: true

jobs:
  extract-and-push:
    runs-on: ubuntu-20.04

    env:
      DUMP_URL: ${{ github.event.inputs.link }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      PUBLIC_SSH_KEY: ${{ secrets.PUBLIC_SSH }}
      PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH }}
      USE_ALT_DUMPER: "true"

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-codeql: true
          remove-haskell: true
          remove-docker-images: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y curl jq wget axel aria2 unace unrar zip unzip \
                             p7zip-full p7zip-rar sharutils rar uudeview mpack arj \
                             cabextract rename liblzma-dev brotli lz4 python-is-python3 \
                             python3 python3-dev python3-pip git gawk sudo cpio ripgrep detox device-tree-compiler

      - name: Install Python packages
        run: |
          python3 -m pip install backports.lzma protobuf pycrypto aospdtgen extract-dtb dumpyara gdown
          python3 -m pip install git+https://github.com/Juvenal-Yescas/mediafire-dl

      - name: Run dumping firmware
        run: |
          sudo mv dumper.sh /usr/local/bin/dumper
          chmod +x /usr/local/bin/dumper
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
          echo "${PRIVATE_SSH_KEY}" > ~/.ssh/id_ed25519
          echo "${PUBLIC_SSH_KEY}" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          chmod 644 ~/.ssh/id_ed25519.pub
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          dumper $DUMP_URL "${GIT_TOKEN}"
